config/routes.rb
Imadoko::Application.routes.draw do
  root 'races#index'

  resources :races
  resources :entries

  namespace :cron do
    get :crawl
  end
end

app/models/crawler/base.rb
module Crawler
  class Base
    attr_accessor :entry

    def crawl
      raise 'not implemented.'
    end
  end
end

app/models/crawler/tokyo.rb
# -*- coding: utf-8 -*-
module Crawler
  class Tokyo < Base
    def url
      "http://p.tokyo42195.org/numberfile/#{@entry.number}.html"
    end

    def crawl
    end

    def fetch
      doc = nil
      open(self.url) do |data|
        doc = Nokogiri::HTML(data)
      end

      # index  |         <dt>           |       <dd>
      # -------+------------------------+-----------------
      #   0    |   ナンバー(Bib number) |  99999999
      #   1    |   氏名(Name)           |  苗字&nbsp;名前
      #   2    |   種目(Category)       |  マラソン男子

      unless doc.css('#frame dd').map(&:text).first == @entry.number
        raise 'bib number mismatched.'
      end

      # th[1]        th[2]                      th[3]     th[4]
      #----------------------------------------------------------
      # 地点名  スプリット （ネットタイム）   ラップ    通過時間
      # Point     Split    （Net Time）         Lap       Time

      # td[1]        td[2]                      td[3]     td[4]
      #----------------------------------------------------------
      # 5km     00:20:40　(0:20:20)           0:20:20   09:30:40
      # 10km    00:41:10　(0:40:50)           0:20:30   09:51:10
      # 15km    01:01:49　(1:01:29)           0:20:39   10:11:49
      # 20km    01:22:40　(1:22:20)           0:20:51   10:32:40
      # 25km    01:43:13　(1:42:53)           0:20:33   10:53:13
      # 30km    02:03:59　(2:03:39)           0:20:46   11:13:59
      # 35km    02:24:58　(2:24:38)           0:20:59   11:34:58
      # 40km    02:46:42　(2:46:22)           0:21:44   11:56:42
      # Finish  02:56:21　(2:56:01)           0:09:39   12:06:21

      doc.search("//table[@class='sarchList']//tr[position()>1]").map do |tr|
        {
          point: tr.search("td[1]").text,  #=> 5km
          split: tr.search("td[2]").text,  #=> 00:20:40　(0:20:20)
          lap:   tr.search("td[3]").text,  #=> 0:20:20
          time:  tr.search("td[4]").text,  #=> 09:30:40
        }
      end
    end

    # 現在位置、ゴール時刻を予測する
    def calc_expectancy hash
      now_time = Time.now
      passed_time = Time.parse(hash[:time ])

      reg = Regexp.new("[0-9]*km", Regexp::IGNORECASE)

      if reg.match(hash[:point]) && hash[:point].to_i % 5 == 0

        progress_sec = now_time.to_i - passed_time.to_i # 最終地点を通過してからの経過時間
        lap_time = Time.parse(hash[:lap])                                  # ラップタイム
        lap_sec  = lap_time.hour * 3600 + lap_time.min * 60 + lap_time.sec # ラップタイム(秒）
        speed_per_second = 5000.0 / lap_sec.to_f        # 秒速

        hash[:now_point] = progress_sec * speed_per_second / 1000.0 + hash[:point].to_i # 現在位置(Km)

        /([0-9:]+)　*([0-9:]+)/ =~ hash[:split].gsub(/[()]/, '')
        gross_time = Time.parse(Regexp.last_match(1))   # スプリット グロス
        net_time = Time.parse(Regexp.last_match(2))     # スプリット ネット

        required_time = (42.195 - hash[:point].to_i.to_f ) * (lap_sec / 5.0) # ゴールまでに必要な時間

        hash[:gross_expectancy] = gross_time + required_time # ゴール予測（グロス）
        hash[:net_expectancy  ] = net_time   + required_time # ゴール予測（ネット）

      else
        hash[:now_point       ] = nil
        hash[:gross_expectancy] = nil
        hash[:net_expectancy  ] = nil
      end
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :race
  has_many :footprints, dependent: :destroy

  STATUSES = [nil, 'running', 'finished', 'dns', 'dnf']

  validates_presence_of :race_id
  validates_presence_of :number
  validates_inclusion_of :status, in: STATUSES

  scope :running, -> do
    where(status: 'running')
  end

  def crawl
    crawler = self.race.create_crawler(self)
    crawler.crawl
  end
end

app/models/footprint.rb
class Footprint < ActiveRecord::Base
  belongs_to :entry

  validates_presence_of :entry_id
  validates_presence_of :distance
  validates_presence_of :passed_at
end

app/models/race.rb
class Race < ActiveRecord::Base
  has_many :entries, dependent: :destroy

  validates_presence_of :label
  validates_presence_of :url
  validates_presence_of :distance

  module Distance
    FULL_MARATHON = 42.195
    HALF_MARATHON = FULL_MARATHON / 2
  end

  def create_crawler entry
    self.crawler.constantize.new.tap do |crawler|
      crawler.entry = entry
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cron_controller.rb
class CronController < ApplicationController
  def crawl
    @entries = Entry.running
    @entries.each do |entry|
      entry.delay.crawl
    end
    render text: 'ok'
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:race_id, :number, :status)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: [:show, :edit, :update, :destroy]

  # GET /races
  # GET /races.json
  def index
    @races = Race.all
  end

  # GET /races/1
  # GET /races/1.json
  def show
  end

  # GET /races/new
  def new
    @race = Race.new
  end

  # GET /races/1/edit
  def edit
  end

  # POST /races
  # POST /races.json
  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to @race, notice: 'Race was successfully created.' }
        format.json { render action: 'show', status: :created, location: @race }
      else
        format.html { render action: 'new' }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /races/1
  # PATCH/PUT /races/1.json
  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to @race, notice: 'Race was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /races/1
  # DELETE /races/1.json
  def destroy
    @race.destroy
    respond_to do |format|
      format.html { redirect_to races_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_race
      @race = Race.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def race_params
      params.require(:race).permit(:label, :url, :crawler, :distance, :starts_at, :ends_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cron_helper.rb
module CronHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/entries/_form.html.slim
= form_for @entry do |f|
  - if @entry.errors.any?
    #error_explanation
      h2 = "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      ul
        - @entry.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :race
    = f.text_field :race
  .field
    = f.label :number
    = f.text_field :number
  .field
    = f.label :status
    = f.text_field :status
  .actions = f.submit 'Save'

app/views/entries/edit.html.slim
h1 Editing entry

== render 'form'

= link_to 'Show', @entry
'|
= link_to 'Back', entries_path

app/views/entries/index.html.slim
h1 Listing entries

table
  tr
    th Race
    th Number
    th Status
    th
    th
    th

  - @entries.each do |entry|
    tr
      td = entry.race
      td = entry.number
      td = entry.status
      td = link_to 'Show', entry
      td = link_to 'Edit', edit_entry_path(entry)
      td = link_to 'Destroy', entry, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Entry', new_entry_path

app/views/entries/new.html.slim
h1 New entry

== render 'form'

= link_to 'Back', entries_path

app/views/entries/show.html.slim
p#notice = notice

p
  strong Race:
  = @entry.race
p
  strong Number:
  = @entry.number
p
  strong Status:
  = @entry.status

= link_to 'Edit', edit_entry_path(@entry)
'|
= link_to 'Back', entries_path

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Imadoko"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    .navbar.navbar-static-top
        .container
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#"Imadoko
          .nav-collapse.collapse.navbar-responsive-collapse
            ul.nav.navbar-nav
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li= link_to "Link 1", "/path1"
              li= link_to "Link 2", "/path2"
              li= link_to "Link 3", "/path3"

      footer
        p &copy; Company 2013

app/views/races/_form.html.slim
= form_for @race do |f|
  - if @race.errors.any?
    #error_explanation
      h2 = "#{pluralize(@race.errors.count, "error")} prohibited this race from being saved:"
      ul
        - @race.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :label
    = f.text_field :label
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :crawler
    = f.text_field :crawler
  .field
    = f.label :distance
    = f.text_field :distance
  .field
    = f.label :starts_at
    = f.datetime_select :starts_at
  .field
    = f.label :ends_at
    = f.datetime_select :ends_at
  .actions = f.submit 'Save'

app/views/races/edit.html.slim
h1 Editing race

== render 'form'

= link_to 'Show', @race
'|
= link_to 'Back', races_path

app/views/races/index.html.slim
h1 Listing races

table
  tr
    th Label
    th Url
    th Crawler
    th Distance
    th Starts at
    th Ends at
    th
    th
    th

  - @races.each do |race|
    tr
      td = race.label
      td = race.url
      td = race.crawler
      td = race.distance
      td = race.starts_at
      td = race.ends_at
      td = link_to 'Show', race
      td = link_to 'Edit', edit_race_path(race)
      td = link_to 'Destroy', race, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Race', new_race_path

app/views/races/new.html.slim
h1 New race

== render 'form'

= link_to 'Back', races_path

app/views/races/show.html.slim
p#notice = notice

p
  strong Label:
  = @race.label
p
  strong Url:
  = @race.url
p
  strong Crawler:
  = @race.crawler
p
  strong Distance:
  = @race.distance
p
  strong Starts at:
  = @race.starts_at
p
  strong Ends at:
  = @race.ends_at

= link_to 'Edit', edit_race_path(@race)
'|
= link_to 'Back', races_path